import { defineConfig } from "vite";
import laravel from "laravel-vite-plugin";

export default defineConfig({
    plugins: [
        laravel({
            input: [
                // Theme Css
                'resources/scss/app.scss',
                'resources/scss/icons.scss',

                'node_modules/animate.css/animate.min.css',
                'node_modules/animate.css/animate.compat.css',
                'node_modules/glightbox/dist/css/glightbox.min.css',
                'node_modules/plyr/dist/plyr.css',
                'node_modules/nouislider/dist/nouislider.min.css',
                'node_modules/sweetalert2/dist/sweetalert2.min.css',
                'node_modules/swiper/swiper-bundle.min.css',
                'node_modules/tippy.js/dist/tippy.css',
                'node_modules/shepherd.js/dist/css/shepherd.css',
                'node_modules/quill/dist/quill.core.css',
                'node_modules/quill/dist/quill.bubble.css',
                'node_modules/quill/dist/quill.snow.css',
                'node_modules/dropzone/dist/min/dropzone.min.css',
                'node_modules/flatpickr/dist/flatpickr.min.css',
                'node_modules/@simonwep/pickr/dist/themes/classic.min.css',
                'node_modules/@simonwep/pickr/dist/themes/monolith.min.css',
                'node_modules/@simonwep/pickr/dist/themes/nano.min.css',
                'node_modules/nouislider/dist/nouislider.min.css',
                'node_modules/nice-select2/dist/css/nice-select2.css',
                'node_modules/jsvectormap/dist/css/jsvectormap.min.css',
                'node_modules/glightbox/dist/css/glightbox.min.css',
                'node_modules/gridjs/dist/theme/mermaid.min.css',
                // 'node_modules/dropzone/dist/min/dropzone.min.js',
                'node_modules/dropzone/dist/min/dropzone.min.js',

                // Theme Js
                'resources/js/config.js',
                'resources/js/app.js',
                'resources/js/head.js',

                'resources/js/pages/dashboard.js',
                'resources/js/pages/apps-calendar.js',
                'resources/js/pages/apps-kanban.js',
                'resources/js/pages/extended-animation.js',
                'resources/js/pages/extended-sortable.js',
                'resources/js/pages/extended-plyr.js',
                'resources/js/pages/extended-sweetalert.js',
                'resources/js/pages/extended-swiper.js',
                'resources/js/pages/extended-tippy.js',
                'resources/js/pages/extended-tour.js',
                'resources/js/pages/auth/login.js',
                'resources/js/pages/form-inputmask.js',
                'resources/js/pages/form-fileupload.js',
                'resources/js/pages/form-flatpickr.js',
                'resources/js/pages/extended-ratings.js',
                'resources/js/pages/form-editor.js',
                'resources/js/pages/extended-lightbox.js',
                'resources/js/pages/form-color-pickr.js',
                'resources/js/pages/form-rangeslider.js',
                'resources/js/pages/form-select.js',
                'resources/js/pages/form-validation.js',
                'resources/js/pages/icons-material-symbols.js',
                'resources/js/pages/icons-mingcute.js',
                'resources/js/pages/icons-feather.js',
                'resources/js/pages/maps-google.js',
                'resources/js/pages/maps-vector.js',
                'resources/js/pages/gallery.js',
                'resources/js/pages/table-gridjs.js',
                'resources/js/pages/charts-apex.js',
                'resources/js/pages/extended-toastify.js',

                // Code Highlight Js
                'resources/js/pages/highlight.js',

                // Core & Utils
                'resources/js/bootstrap.js',
                'resources/js/ziggy.js',
                'resources/js/core/data-table.js',
                'resources/js/core/form-handler.js',
                'resources/js/core/modal-handler.js',
                'resources/js/core/notification.js',
                'resources/js/utils/ajax.js',
                'resources/js/utils/authorization.js',
                'resources/js/utils/format.js',
                'resources/js/utils/index.js',
                'resources/js/utils/validation.js',
                'resources/js/custom/dashboard/index.js',
                'resources/js/custom/export/index.js',

                // Access Module
                'resources/js/custom/access/roles/roles-create.js',
                'resources/js/custom/access/roles/roles-read.js',
                'resources/js/custom/access/roles/roles-edit.js',
                'resources/js/custom/access/roles/roles-delete.js',
                'resources/js/custom/access/users/users-create.js',
                'resources/js/custom/access/users/users-read.js',
                'resources/js/custom/access/users/users-edit.js',
                'resources/js/custom/access/users/users-delete.js',
                'resources/js/custom/access/log/log-read.js',
                'resources/js/custom/access/log/log-detail.js',
                
                // Purchase Module - Updated structure
                'resources/js/custom/purchase/purchase-request/index.js',
                'resources/js/custom/purchase/purchase-request/pr-create.js',
                'resources/js/custom/purchase/purchase-request/pr-update.js',
                'resources/js/custom/purchase/purchase-request/pr-read.js',
                'resources/js/custom/purchase/purchase-request/pr-delete.js',
                'resources/js/custom/purchase/purchase-order/index.js',
                'resources/js/custom/purchase/purchase-order/po-create.js',
                'resources/js/custom/purchase/purchase-order/po-update.js',
                'resources/js/custom/purchase/purchase-order/po-read.js',
                'resources/js/custom/purchase/purchase-order/po-delete.js',
                'resources/js/custom/purchase/po-onsite/index.js',
                'resources/js/custom/purchase/po-onsite/onsite-create.js',
                'resources/js/custom/purchase/po-onsite/onsite-update.js',
                'resources/js/custom/purchase/po-onsite/onsite-read.js',
                'resources/js/custom/purchase/po-onsite/onsite-delete.js',
                'resources/js/custom/purchase/po-onsite/bulk-edit.js',
                
                // Invoice Module - Updated structure
                'resources/js/custom/invoice/dari-vendor/index.js',
                'resources/js/custom/invoice/dari-vendor/dari-vendor-create.js',
                'resources/js/custom/invoice/dari-vendor/dari-vendor-bulk-edit.js',
                'resources/js/custom/invoice/dari-vendor/dari-vendor-read.js',
                'resources/js/custom/invoice/dari-vendor/dari-vendor-delete.js',
                'resources/js/custom/invoice/pengajuan/index.js',
                'resources/js/custom/invoice/pengajuan/pengajuan-create.js',
                'resources/js/custom/invoice/pengajuan/pengajuan-read.js',
                'resources/js/custom/invoice/pengajuan/pengajuan-bulk-edit.js',
                'resources/js/custom/invoice/pengajuan/history.js',
                'resources/js/custom/invoice/pengajuan/history-index.js',

                // Config Module
                'resources/js/custom/config/location/index.js',
                'resources/js/custom/config/location/location-create.js',
                'resources/js/custom/config/location/location-read.js',
                'resources/js/custom/config/location/location-update.js',
                'resources/js/custom/config/location/location-delete.js',
                'resources/js/custom/config/classification/index.js',
                'resources/js/custom/config/classification/classification-create.js',
                'resources/js/custom/config/classification/classification-read.js',
                'resources/js/custom/config/classification/classification-update.js',
                'resources/js/custom/config/classification/classification-delete.js',
                'resources/js/custom/config/classification/pr-items.js',
                'resources/js/custom/config/supplier/index.js',
                'resources/js/custom/config/supplier/supplier-create.js',
                'resources/js/custom/config/supplier/supplier-read.js',
                'resources/js/custom/config/supplier/supplier-update.js',
                'resources/js/custom/config/supplier/supplier-delete.js',
                
                // Pembayaran Module
                'resources/js/custom/invoice/pembayaran/index.js',
                'resources/js/custom/invoice/pembayaran/pembayaran-read.js',
                'resources/js/custom/invoice/pembayaran/pembayaran-create.js',
                'resources/js/custom/invoice/pembayaran/pembayaran-edit.js',
            

            ],
            refresh: true
        }),
    ],
});
